### ISSUE TITLE
Upgrade to BenchmarkDotNet 0.13.2

### ISSUE THREAD

**Issue by mawosoft** [mawosoft/Mawosoft.Extensions.BenchmarkDotNet#117]
Due to various changes to the Public API surface of BenchmarkDotNet, neither Mawosoft.Extensions.BenchmarkDotNet 0.2.2 nor the CI builds up to 0.2.3-dev.110 currently support BenchmarkDotNet 0.13.2.

The currently supported BDN versions are 0.13.1 - 0.13.1.1864 (nightly).

Related issues: #116, #115, #104

Required MEB adjustments for BDN 0.13.2:
- [x] Bump BDN dependency to 0.13.2 and remove transitive pinning for System.Management.
- [x] Changed ctor of `BenchmarkDotNet.Reports.Summary`
- [x] Resync ApiCompat wrappers for `BenchmarkReport`, `ExecuteResult`, and `GenerateResult`
- [x] ~Should we add a `ReplaceColumnHidingRules` method to `ConfigExtensions`?~ Moved to #122

Required test adjustments:
- [x] Adjust for members added to `IConfig` and its implementations (`ManualConfig` etc) in `ConfigExtensionsTests.cs`.
Note that `GetColumnHidingRules` doesn't have a corresponding `AddXxx` method, but multiple `HideColumn` overloads instead.
- [x] `BaselineAllocationRatioColumn` introduced in 0.13.1.x uses the private ctor/static instance model. Affects `ColumnCategoryExtensionsTests.cs`

Changes to consider due to enhancements and fixes in BDN 0.13.2:
- [x] ~`HideColumns` (attribute, API, cmdline) possibly renders `JobColumnSelectionProvider` obsolete.~ Moved to #122
- [x] ~`HideColumns` may affect `WhatifFilter.cs`~ Moved to #122
- [x] **docfx:** Private copy of BDN's xrefmap no longer necessary.
- [x] **ApiCompat:** Change BDN baseline to 0.13.2
- [x] ~**ApiCompat:** BDN now has multiple TFMs. Should they be included in API Compat Check or is `netstandard2.0` sufficient?~ Moved to #123
